version: 2
jobs:
  build:
    working_directory: /go/src/github.com/lmorg/murex
    docker:
      - image: lmorg/murex
        environment:
          GOPATH: /go
    
    steps:
      - run:
          name: Nuke old code
          command: cd .. && rm -rf murex && mkdir murex

      - checkout

      - run:
          name: Run CI script
          command: test/ci.sh

      - run:
          name: Code Coverage (codecov.io)
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
